/*
 * Copyright (c) 2015 Vehbi Sinan Tunalioglu <vst@vsthost.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.vsthost.rnd.jdeoptim;

import org.apache.commons.math3.random.RandomGenerator;

/**
 * Provides a generic strategy interface.
 */
public interface Strategy {
    /**
     * Generates and returns a new population with the given parameters.
     *
     * @param population The last available population.
     * @param scores Scores for each member of the last available population.
     * @param order The order of scores for each member of the last available population, the earlier the element the fitter the member.
     * @param context The additional data context.
     * @param randomGenerator The random number generator.
     * @return A new population generated by the strategy.
     */
    public double[] repopulate(double[][] population, double[] scores, int[] order, Context context, RandomGenerator randomGenerator);
}
